#pragma once

namespace Algorithm {

enum class SortAlgorithm {
  BUBBLE_SORT,
  SELECTION_SORT,
  INSERTION_SORT,
  MERGE_SORT,
  QUICK_SORT,
  HEAP_SORT,
  SHELL_SORT,
  RADIX_SORT,
  COUNTING_SORT,
  BUCKET_SORT,
  RADIX_LSD_SORT,
  RADIX_MSD_SORT
};

enum class SearchAlgorithm {
  BINARY_SEARCH,
  LINEAR_SEARCH,
  JUMP_SEARCH,
  INTERPOLATORY_SEARCH,
  FIBONACCI_SEARCH,
  BINARY_TREE_SEARCH,
  HASH_SEARCH,
  HASH_SEARCH_CHAINING,
  HASH_SEARCH_OPEN_ADDRESSING,
  HASH_SEARCH_DOUBLE_HASHING
};

}
